# Generated by Django 4.2.3 on 2023-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('review', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
